name = "StrongMotionFiles"
uuid = "59272c94-9b39-11ed-2290-fd786acdb13d"
authors = ["Michael Tahedl <michael.ta@icloud.com>"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
